version: '3'
services:
    mysql:
        image: mysql:9.4
        ports:
            - "3306:3306"
        environment:
            - TZ=Asia/Singapore
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql_data/seed-data:/docker-entrypoint-initdb.d
volumes:
    mysql-data:
