version: '3'
services: 
    redis:
        image: redis/redis-stack:7.4.0-v6
        ports:
            - "6379:6379"
        environment:
            - REDIS_ARGS="--requirepass redis_pass"
        volumes:
            - redis-data:/data
volumes:
    redis-data:
