services: 
    server:
        build: .
        image: dev-image-ai-ml
        user: ubuntu
        environment: 
            - TZ=Asia/Singapore
            - OPENAI_BASE_URL=http://model-runner.docker.internal/engines/v1
            - OPENAI_API_KEY=your-default-key
        volumes:
            - ..:/workspaces/playground-ai-ml:delegated
            - ../../shared-data:/workspaces/shared-data:delegated
        working_dir: /workspaces/playground-ai-ml
