services: 
    server:
        build: .
        image: dev-image-ai-ml
        user: ubuntu
        environment: 
            - TZ=Asia/Singapore
        volumes:
            - ..:/home/ubuntu/playground-ai-ml:delegated
            - ../../shared-data:/home/ubuntu/shared-data:delegated
        working_dir: /home/ubuntu/playground-ai-ml
