version: '3'
services: 
    redis:
        image: redis/redis-stack:7.4.0-v2
        environment:
            - REDIS_ARGS="--requirepass redis_pass"
        volumes:
            - redis-data:/data
volumes:
    redis-data:
